import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { loadRepositoryKnowledge } from './repository.ts';
import { compareIds } from '../../core/knowledge/normalization.ts';
import type { ConceptCard } from '../../core/knowledge/model.ts';
import { validateConceptCards } from '../../core/knowledge/validation.ts';

export function serializeCorpus(cards: readonly ConceptCard[]): string {
  const validated = validateConceptCards(cards).sort((a, b) =>
    compareIds(a.id, b.id),
  );
  return (
    '// GENERATED by npm run knowledge:build. Do not edit. Canonical corpus only.\n' +
    "import type { ConceptCard } from '../core/knowledge/model.ts';\n" +
    `export const canonicalKnowledge: ConceptCard[] = ${JSON.stringify(validated, null, 2)};\n`
  );
}
export async function buildKnowledge(): Promise<number> {
  const cards = await loadRepositoryKnowledge();
  const directory = new URL('../../generated/', import.meta.url);
  const target = new URL('knowledge.ts', directory);
  const source = serializeCorpus(cards);
  await mkdir(directory, { recursive: true });
  let previous: string | undefined;
  try {
    previous = await readFile(target, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }
  if (previous !== source) await writeFile(target, source);
  return cards.length;
}
// Keep generation explicit, so tests can inspect serialization without filesystem writes.
export const generatedKnowledgePath = fileURLToPath(
  new URL('../../generated/knowledge.ts', import.meta.url),
);
